version: "3.8"

services:
  postgres-db:
    image: postgres:15
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_DB: careconnect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "15432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-boot-app:
    build: .
    container_name: springboot-container
    restart: always
    depends_on:
      - postgres-db
    env_file:
      - .env
    ports:
      - "8080:8080"

volumes:
  pgdata:
